name: Deploy WP Theme to prod

on:
  push:
    paths:
      - "wp-content/themes/super-toat/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
          
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
  
      - name: preparation
        run: rm -rf ./*
        working-directory: wp-content/themes/super-toat

      - name: test1
        run: ls -al wp-content/themes/super-toat/src

      - name: test2
        run: cat wp-content/themes/super-toat/src/parcel-entrypoint.js

      - name: test3
        run: cat ./wp-content/themes/super-toat/src/parcel-entrypoint.js

      - name: test4
        run: npm run test4
      
      - name: install npm dependencies
        run:  npm install
        
      - name: build
        run:  npm run github-build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.PROD_WP_FTP_SERVER }}
          ftp-username: ${{ secrets.PROD_WP_FTP_USERNAME }}
          ftp-password: ${{ secrets.PROD_WP_FTP_PASSWORD }}
          local-dir: wp-content/themes
