name: Deploy WP Theme to prod

on:
  push:
    paths:
      - "wp-content/themes/super-toat/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.PROD_WP_FTP_SERVER }}
        ftp-username: ${{ secrets.PROD_WP_FTP_USERNAME }}
        ftp-password: ${{ secrets.PROD_WP_FTP_PASSWORD }}
        local-dir: wp-content/themes
